### ISSUE TITLE
How does this differ from minetest.after?

### ISSUE THREAD

**Issue by rubenwardy** [HybridDog/function_delayer#1]

**Comment by HybridDog** [comment]
minetest.after executes the function after a specific time (and not exactly if it's lagging (dtime can be long))
and minetest.delay_function executes the function after a specific time only if it's lagging, the function can be and is usually executed earlier.

If you e.g. want to grow 1000 big trees you can
either place them all at once and need to wait long until you can play again
or you can use minetest.delay_function to let the trees grow in globalsteps with time limit. e.g. growing of a couple of trees is not allowed to take more than 1s but all trees have to been grown after a specific time 

l forgot to subtract dtime from ts that not only the lag of functions added with minetest.delay_function are disallowed to take more than 1s.
